---
- name: Install direnv
  community.general.homebrew:
    name: direnv
    state: latest

- name: Check if direnv plugin is enabled in .zshrc
  ansible.builtin.shell: grep '^plugins=' "{{ lookup('env', 'HOME') }}/.zshrc" | grep -qE '(\(|[[:space:]])direnv([[:space:]]|\))'
  register: direnv_check
  changed_when: false
  failed_when: false

- name: Enable direnv oh-my-zsh plugin
  ansible.builtin.shell: sed -i '' 's/^plugins=(\(.*\))/plugins=(\1 direnv)/' "{{ lookup('env', 'HOME') }}/.zshrc"
  when: direnv_check.rc != 0
