---
- name: Install direnv
  community.general.homebrew:
    name: direnv
    state: latest

- name: Enable direnv oh-my-zsh plugin in .zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/.zshrc"
    regexp: '^(plugins=\((?!.*\bdirenv\b).*)\)$'
    line: '\1 direnv)'
    backrefs: true
