---
- name: Install Go via mise
  ansible.builtin.command: mise use --global go@latest
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:{{ lookup('env', 'HOME') }}/.local/bin"
  register: mise_go
  changed_when: "'installed' in mise_go.stderr"
