---
- name: Install bun # noqa: command-instead-of-module risky-shell-pipe
  ansible.builtin.shell: curl -fsSL https://bun.com/install | bash
  args:
    creates: "{{ lookup('env', 'HOME') }}/.bun/bin/bun"
